
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("33853283-9d9c-40cf-a2be-6e5e0fd2073c")>
#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class PushModelContainer
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new PushModelContainer object using the connection string found in the 'PushModelContainer' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=PushModelContainer", "PushModelContainer")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new PushModelContainer object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "PushModelContainer")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new PushModelContainer object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "PushModelContainer")
        MyBase.ContextOptions.LazyLoadingEnabled = true
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property DeviceTokens() As ObjectSet(Of DeviceToken)
        Get
            If (_DeviceTokens Is Nothing) Then
                _DeviceTokens = MyBase.CreateObjectSet(Of DeviceToken)("DeviceTokens")
            End If
            Return _DeviceTokens
        End Get
    End Property

    Private _DeviceTokens As ObjectSet(Of DeviceToken)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property LastDeals() As ObjectSet(Of LastDeal)
        Get
            If (_LastDeals Is Nothing) Then
                _LastDeals = MyBase.CreateObjectSet(Of LastDeal)("LastDeals")
            End If
            Return _LastDeals
        End Get
    End Property

    Private _LastDeals As ObjectSet(Of LastDeal)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the DeviceTokens EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToDeviceTokens(ByVal deviceToken As DeviceToken)
        MyBase.AddObject("DeviceTokens", deviceToken)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the LastDeals EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToLastDeals(ByVal lastDeal As LastDeal)
        MyBase.AddObject("LastDeals", lastDeal)
    End Sub

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="PushModel", Name:="DeviceToken")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class DeviceToken
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new DeviceToken object.
    ''' </summary>
    ''' <param name="token">Initial value of the Token property.</param>
    ''' <param name="appName">Initial value of the AppName property.</param>
    ''' <param name="development">Initial value of the Development property.</param>
    ''' <param name="badgeCount">Initial value of the BadgeCount property.</param>
    ''' <param name="active">Initial value of the Active property.</param>
    Public Shared Function CreateDeviceToken(token As Global.System.String, appName As Global.System.String, development As Global.System.Boolean, badgeCount As Global.System.Int32, active As Global.System.Boolean) As DeviceToken
        Dim deviceToken as DeviceToken = New DeviceToken
        deviceToken.Token = token
        deviceToken.AppName = appName
        deviceToken.Development = development
        deviceToken.BadgeCount = badgeCount
        deviceToken.Active = active
        Return deviceToken
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Token() As Global.System.String
        Get
            Return _Token
        End Get
        Set
            If (_Token <> Value) Then
                OnTokenChanging(value)
                ReportPropertyChanging("Token")
                _Token = StructuralObject.SetValidValue(value, false)
                ReportPropertyChanged("Token")
                OnTokenChanged()
            End If
        End Set
    End Property

    Private _Token As Global.System.String
    Private Partial Sub OnTokenChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTokenChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property AppName() As Global.System.String
        Get
            Return _AppName
        End Get
        Set
            OnAppNameChanging(value)
            ReportPropertyChanging("AppName")
            _AppName = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("AppName")
            OnAppNameChanged()
        End Set
    End Property

    Private _AppName As Global.System.String
    Private Partial Sub OnAppNameChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnAppNameChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Development() As Global.System.Boolean
        Get
            Return _Development
        End Get
        Set
            OnDevelopmentChanging(value)
            ReportPropertyChanging("Development")
            _Development = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Development")
            OnDevelopmentChanged()
        End Set
    End Property

    Private _Development As Global.System.Boolean
    Private Partial Sub OnDevelopmentChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnDevelopmentChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property BadgeCount() As Global.System.Int32
        Get
            Return _BadgeCount
        End Get
        Set
            OnBadgeCountChanging(value)
            ReportPropertyChanging("BadgeCount")
            _BadgeCount = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("BadgeCount")
            OnBadgeCountChanged()
        End Set
    End Property

    Private _BadgeCount As Global.System.Int32
    Private Partial Sub OnBadgeCountChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnBadgeCountChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Active() As Global.System.Boolean
        Get
            Return _Active
        End Get
        Set
            OnActiveChanging(value)
            ReportPropertyChanging("Active")
            _Active = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Active")
            OnActiveChanged()
        End Set
    End Property

    Private _Active As Global.System.Boolean
    Private Partial Sub OnActiveChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnActiveChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property LastActivity() As Nullable(Of Global.System.DateTime)
        Get
            Return _LastActivity
        End Get
        Set
            OnLastActivityChanging(value)
            ReportPropertyChanging("LastActivity")
            _LastActivity = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("LastActivity")
            OnLastActivityChanged()
        End Set
    End Property

    Private _LastActivity As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnLastActivityChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnLastActivityChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="PushModel", Name:="LastDeal")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class LastDeal
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new LastDeal object.
    ''' </summary>
    ''' <param name="id">Initial value of the id property.</param>
    ''' <param name="headline">Initial value of the headline property.</param>
    ''' <param name="body">Initial value of the body property.</param>
    ''' <param name="image">Initial value of the image property.</param>
    ''' <param name="isExpired">Initial value of the isExpired property.</param>
    ''' <param name="datePosted">Initial value of the datePosted property.</param>
    ''' <param name="legacy">Initial value of the legacy property.</param>
    ''' <param name="hot">Initial value of the hot property.</param>
    ''' <param name="free">Initial value of the free property.</param>
    Public Shared Function CreateLastDeal(id As Global.System.Int32, headline As Global.System.String, body As Global.System.String, image As Global.System.String, isExpired As Global.System.Boolean, datePosted As Global.System.DateTime, legacy As Global.System.Boolean, hot As Global.System.Boolean, free As Global.System.Boolean) As LastDeal
        Dim lastDeal as LastDeal = New LastDeal
        lastDeal.id = id
        lastDeal.headline = headline
        lastDeal.body = body
        lastDeal.image = image
        lastDeal.isExpired = isExpired
        lastDeal.datePosted = datePosted
        lastDeal.legacy = legacy
        lastDeal.hot = hot
        lastDeal.free = free
        Return lastDeal
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property id() As Global.System.Int32
        Get
            Return _id
        End Get
        Set
            If (_id <> Value) Then
                OnidChanging(value)
                ReportPropertyChanging("id")
                _id = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("id")
                OnidChanged()
            End If
        End Set
    End Property

    Private _id As Global.System.Int32
    Private Partial Sub OnidChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnidChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property headline() As Global.System.String
        Get
            Return _headline
        End Get
        Set
            OnheadlineChanging(value)
            ReportPropertyChanging("headline")
            _headline = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("headline")
            OnheadlineChanged()
        End Set
    End Property

    Private _headline As Global.System.String
    Private Partial Sub OnheadlineChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnheadlineChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property body() As Global.System.String
        Get
            Return _body
        End Get
        Set
            OnbodyChanging(value)
            ReportPropertyChanging("body")
            _body = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("body")
            OnbodyChanged()
        End Set
    End Property

    Private _body As Global.System.String
    Private Partial Sub OnbodyChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnbodyChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property image() As Global.System.String
        Get
            Return _image
        End Get
        Set
            OnimageChanging(value)
            ReportPropertyChanging("image")
            _image = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("image")
            OnimageChanged()
        End Set
    End Property

    Private _image As Global.System.String
    Private Partial Sub OnimageChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnimageChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property isExpired() As Global.System.Boolean
        Get
            Return _isExpired
        End Get
        Set
            OnisExpiredChanging(value)
            ReportPropertyChanging("isExpired")
            _isExpired = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("isExpired")
            OnisExpiredChanged()
        End Set
    End Property

    Private _isExpired As Global.System.Boolean
    Private Partial Sub OnisExpiredChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnisExpiredChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property datePosted() As Global.System.DateTime
        Get
            Return _datePosted
        End Get
        Set
            OndatePostedChanging(value)
            ReportPropertyChanging("datePosted")
            _datePosted = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("datePosted")
            OndatePostedChanged()
        End Set
    End Property

    Private _datePosted As Global.System.DateTime
    Private Partial Sub OndatePostedChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OndatePostedChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property legacy() As Global.System.Boolean
        Get
            Return _legacy
        End Get
        Set
            OnlegacyChanging(value)
            ReportPropertyChanging("legacy")
            _legacy = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("legacy")
            OnlegacyChanged()
        End Set
    End Property

    Private _legacy As Global.System.Boolean
    Private Partial Sub OnlegacyChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnlegacyChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property hot() As Global.System.Boolean
        Get
            Return _hot
        End Get
        Set
            OnhotChanging(value)
            ReportPropertyChanging("hot")
            _hot = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("hot")
            OnhotChanged()
        End Set
    End Property

    Private _hot As Global.System.Boolean
    Private Partial Sub OnhotChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnhotChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property free() As Global.System.Boolean
        Get
            Return _free
        End Get
        Set
            OnfreeChanging(value)
            ReportPropertyChanging("free")
            _free = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("free")
            OnfreeChanged()
        End Set
    End Property

    Private _free As Global.System.Boolean
    Private Partial Sub OnfreeChanging(value As Global.System.Boolean)
    End Sub

    Private Partial Sub OnfreeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property price() As Global.System.String
        Get
            Return _price
        End Get
        Set
            OnpriceChanging(value)
            ReportPropertyChanging("price")
            _price = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("price")
            OnpriceChanged()
        End Set
    End Property

    Private _price As Global.System.String
    Private Partial Sub OnpriceChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnpriceChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property slug() As Global.System.String
        Get
            Return _slug
        End Get
        Set
            OnslugChanging(value)
            ReportPropertyChanging("slug")
            _slug = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("slug")
            OnslugChanged()
        End Set
    End Property

    Private _slug As Global.System.String
    Private Partial Sub OnslugChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnslugChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property sHeadline() As Global.System.String
        Get
            Return _sHeadline
        End Get
        Set
            OnsHeadlineChanging(value)
            ReportPropertyChanging("sHeadline")
            _sHeadline = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("sHeadline")
            OnsHeadlineChanged()
        End Set
    End Property

    Private _sHeadline As Global.System.String
    Private Partial Sub OnsHeadlineChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnsHeadlineChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property author() As Global.System.String
        Get
            Return _author
        End Get
        Set
            OnauthorChanging(value)
            ReportPropertyChanging("author")
            _author = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("author")
            OnauthorChanged()
        End Set
    End Property

    Private _author As Global.System.String
    Private Partial Sub OnauthorChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnauthorChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property expirationDate() As Nullable(Of Global.System.DateTime)
        Get
            Return _expirationDate
        End Get
        Set
            OnexpirationDateChanging(value)
            ReportPropertyChanging("expirationDate")
            _expirationDate = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("expirationDate")
            OnexpirationDateChanged()
        End Set
    End Property

    Private _expirationDate As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnexpirationDateChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnexpirationDateChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property images() As Global.System.String
        Get
            Return _images
        End Get
        Set
            OnimagesChanging(value)
            ReportPropertyChanging("images")
            _images = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("images")
            OnimagesChanged()
        End Set
    End Property

    Private _images As Global.System.String
    Private Partial Sub OnimagesChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnimagesChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property C_id() As Global.System.String
        Get
            Return _C_id
        End Get
        Set
            OnC_idChanging(value)
            ReportPropertyChanging("C_id")
            _C_id = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("C_id")
            OnC_idChanged()
        End Set
    End Property

    Private _C_id As Global.System.String
    Private Partial Sub OnC_idChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnC_idChanged()
    End Sub

    #End Region

End Class

#End Region


